# Generated by Django 5.2.3 on 2025-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="type",
            field=models.CharField(default="manger", max_length=50),
        ),
    ]
