# Generated by Django 5.2.3 on 2025-07-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="type",
            field=models.CharField(default="manager", max_length=50),
        ),
    ]
