# Generated by Django 5.2.3 on 2025-08-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_customer_status"),
    ]

    operations = [
                migrations.RenameField(
            model_name="customer",
            old_name="customer_name",
            new_name="customer_neme",
        ),
    ]
