# Generated by Django 5.2.3 on 2025-08-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_returns_of_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="returns_of_customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
