# Generated by Django 5.2.3 on 2025-08-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_returns_of_customer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer_phone",
            field=models.CharField(max_length=30),
        ),
    ]
