# Generated by Django 5.2.3 on 2025-08-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_invoice_customer_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Returns_of_customer",
        ),
    ]
