# Generated by Django 5.2.3 on 2025-08-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_remove_returns_of_customer_customer_and_more"),
        ("sales", "0011_remove_order_customer_remove_order_seller_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceItem",
        ),
        migrations.DeleteModel(
            name="Returns_of_customer",
        ),
    ]
