# Generated by Django 5.2.3 on 2025-08-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0013_initial"),
        ("sales", "0012_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.order",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="customer.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sales.product"
            ),
        ),
        migrations.AddField(
            model_name="returns_of_customer",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer.customer"
            ),
        ),
        migrations.AddField(
            model_name="returns_of_customer",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sales.orderitem"
            ),
        ),
    ]
