# Generated by Django 5.2.3 on 2025-08-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_neme", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=100)),
                ("customer_phone", models.IntegerField()),
                ("customer_address", models.CharField(max_length=100)),
                ("customer_BD", models.DateField(blank=True)),
                ("connect_way", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=100)),
                ("VIP", models.BooleanField(blank=True, default=False)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
