# Generated by Django 5.2.3 on 2025-08-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="customer",
        ),
    ]
