# Generated by Django 5.2.3 on 2025-08-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_rename_neme_to_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="customer_neme",
            new_name="customer_name",
        ),
    ]
