# Generated by Django 5.2.3 on 2025-08-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_returns_of_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returns_of_customer",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="order",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="returns_of_customer",
            name="order_item",
        ),
    ]
