# Generated by Django 5.2.3 on 2025-08-04 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="End_Date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="Start_Date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arabic_name", models.CharField(max_length=255)),
                ("english_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
