# Generated by Django 5.2.3 on 2025-08-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_domain_domain_alter_domain_is_primary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(),
        ),
    ]
