# Generated by Django 5.2.3 on 2025-08-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_alter_tenant_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
