# Generated by Django 5.2.3 on 2025-08-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_alter_tenant_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="no_branches",
            field=models.IntegerField(default=1),
        ),
    ]
