# Generated by Django 5.2.3 on 2025-08-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenant_no_branches"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
