# Generated by Django 5.2.3 on 2025-08-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_delete_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="Activity_Type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
