# Generated by Django 5.2.3 on 2025-08-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenantusers", "0003_refreshtokenstore"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RefreshTokenStore",
            new_name="tenRefreshTokenStore",
        ),
    ]
