# Generated by Django 5.2.3 on 2025-08-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenantusers", "0005_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="contact_phone",
            field=models.IntegerField(blank=True),
        ),
    ]
