# Generated by Django 5.2.3 on 2025-08-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenantusers", "0007_remove_branch_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("Seller", "Seller"),
                    ("kitchen", "Kitchen"),
                    ("delivery", "Delivery"),
                ],
                default="Manager",
                max_length=50,
            ),
        ),
    ]
