# Generated by Django 5.2.3 on 2025-07-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0002_remove_saasuser_userid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
