# Generated by Django 5.2.3 on 2025-07-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saasuser",
            name="UserID",
        ),
    ]
