# Generated by Django 5.2.3 on 2025-08-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0004_refreshtokenstore"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasuser",
            name="is_superuser",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
