# Generated by Django 5.2.3 on 2025-08-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0005_saasuser_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtokenstore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="custom_auth.saasuser"
            ),
        ),
    ]
