# Generated by Django 5.2.3 on 2025-08-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arabic_name", models.CharField(max_length=255)),
                ("english_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("main course", "main course"),
                            ("side dish", "side dish"),
                            ("beverages", "beverages"),
                            ("desserts", "desserts"),
                        ],
                        max_length=255,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(blank=True, upload_to="items/")),
                ("product_no", models.IntegerField(blank=True)),
                ("barcode", models.CharField(max_length=255)),
                ("current_stock", models.IntegerField()),
                ("min_stock", models.IntegerField()),
                ("unit_size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_type", models.CharField(max_length=255)),
                ("status", models.CharField(default="In Stock", max_length=255)),
                (
                    "Supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.supplier"
                    ),
                ),
            ],
        ),
    ]
