# Generated by Django 5.2.3 on 2025-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("gram", "gram"),
                    ("kilogram", "kilogram"),
                    ("liter", "liter"),
                    ("mililiter", "mililiter"),
                    ("piece", "piece"),
                    ("box", "box"),
                    ("carton", "carton"),
                    ("bottle", "bottle"),
                    ("can", "can"),
                    ("pack", "pack"),
                ],
                max_length=255,
            ),
        ),
    ]
