# Generated by Django 5.2.3 on 2025-08-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_product_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
