# Generated by Django 5.2.3 on 2025-08-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_product_suspended_order_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Customer", "Customer"), ("Other", "Other")],
                        max_length=30,
                    ),
                ),
                ("received_from", models.CharField(max_length=255)),
                ("receipt_number", models.IntegerField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paymant_way", models.CharField(max_length=30)),
                ("on_bank", models.CharField(max_length=255)),
                ("purpose", models.TextField(blank=True)),
                ("receiver", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("attachment", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
