# Generated by Django 5.2.3 on 2025-08-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_remove_returns_of_customer_customer_and_more"),
        ("sales", "0010_receipt_check_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="Supplier",
        ),
        migrations.DeleteModel(
            name="Receipt",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
