# Generated by Django 5.2.3 on 2025-08-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0013_initial"),
        ("sales", "0011_remove_order_customer_remove_order_seller_and_more"),
        ("tenantusers", "0008_alter_tenantuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arabic_name", models.CharField(max_length=255, unique=True)),
                ("english_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("main course", "main course"),
                            ("side dish", "side dish"),
                            ("beverages", "beverages"),
                            ("desserts", "desserts"),
                        ],
                        max_length=255,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(blank=True, upload_to="items/")),
                ("product_no", models.IntegerField(blank=True, null=True)),
                ("barcode", models.CharField(blank=True, max_length=255)),
                ("current_stock", models.IntegerField()),
                ("min_stock", models.IntegerField()),
                ("unit_size", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("gram", "gram"),
                            ("kilogram", "kilogram"),
                            ("liter", "liter"),
                            ("mililiter", "mililiter"),
                            ("piece", "piece"),
                            ("box", "box"),
                            ("carton", "carton"),
                            ("bottle", "bottle"),
                            ("can", "can"),
                            ("pack", "pack"),
                        ],
                        max_length=255,
                    ),
                ),
                ("status", models.CharField(default="In Stock", max_length=255)),
                (
                    "suspended",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Customer", "Customer"), ("Other", "Other")],
                        max_length=30,
                    ),
                ),
                ("received_from", models.CharField(max_length=255)),
                ("receipt_number", models.IntegerField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paymant_way", models.CharField(max_length=30)),
                ("check_no", models.IntegerField(blank=True, null=True)),
                ("on_bank", models.CharField(max_length=255)),
                ("purpose", models.TextField(blank=True)),
                ("receiver", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("attachment", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("contact_person", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("join_date", models.DateField()),
                ("address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("payment_terms", models.CharField(default="30 days", max_length=100)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "cash"),
                            ("card", "card"),
                            ("knet", "knet"),
                            ("credit", "credit"),
                        ],
                        max_length=250,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenantusers.tenantuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="Supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.supplier",
            ),
        ),
    ]
