# Generated by Django 5.2.3 on 2025-08-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenantusers", "0002_tenantuser_last_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshTokenStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenantusers.tenantuser",
                    ),
                ),
            ],
        ),
    ]
