# Generated by Django 5.2.3 on 2025-08-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenantusers", "0006_alter_branch_contact_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="tenant",
        ),
    ]
