# Generated by Django 5.2.3 on 2025-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenantusers", "0008_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Manager", "Manager"),
                    ("Seller", "Seller"),
                    ("kitchen", "Kitchen"),
                    ("Delivery", "Delivery"),
                ],
                default="Manager",
                max_length=50,
            ),
        ),
    ]
