# Generated by Django 5.2.3 on 2025-09-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenantusers", "0009_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantuser",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenantuser",
            name="f_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tenantuser",
            name="l_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tenantuser",
            name="licens_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tenantuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="tenantuser",
            name="vehicle_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tenantuser",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
