# Generated by Django 5.2.3 on 2025-08-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_product_product_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.supplier",
            ),
        ),
    ]
