# Generated by Django 5.2.3 on 2025-08-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_product_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="arabic_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="english_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
