# Generated by Django 5.2.3 on 2025-08-26 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("sales", "0007_alter_product_arabic_name_alter_product_english_name"),
        ("tenantusers", "0008_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="suspended",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "cash"),
                            ("card", "card"),
                            ("knet", "knet"),
                            ("credit", "credit"),
                        ],
                        max_length=250,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenantusers.tenantuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.product"
                    ),
                ),
            ],
        ),
    ]
