# Generated by Django 5.2.3 on 2025-08-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="check_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
