# Generated by Django 5.2.3 on 2025-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0013_invoice_invoiceitem_purchaseorder_purchaseorderitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
