# Generated by Django 5.2.3 on 2025-09-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0014_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=250),
        ),
    ]
